# Generated by Django 5.0.6 on 2024-06-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to='uploads/covers'),
        ),
    ]
