# Generated by Django 3.1.7 on 2024-06-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_auto_20240618_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='s_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
