# Generated by Django 5.0.6 on 2024-06-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0013_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
