# Generated by Django 5.0.6 on 2024-06-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0014_alter_review_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='s_description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='short description'),
        ),
    ]
